### ISSUE TITLE
Config directory race between mopidy processes

### ISSUE THREAD

**Issue by tthef** [radiodan/radiodan.js#21]
On startup, mopidy checks if $XDG_CONFIG_HOME/mopid directory tree exists, and if not it creates it. However, there is a race between the three processes the server starts on first boot, all three try to create this directory, and two will abort becaue the directory was already created by the first.

We can work around this by ensuring the directory exists in advance, but I expect the three instances might then fight over the files that they place into there. I'll make the Yocto build to ensure the directory, but I though I should flag this up.

**Comment by tthef** [comment]
Sorry, the directory in question is $XDG_DATA_DIR/mopidy

**Comment by pixelblend** [comment]
I've made some changes to the mopidy config so that each player uses a distinct path. That should prevent the race condition.
